name: Dana_run
on:
 workflow_dispatch: {}
 push:
   branches:
    - "release"
    - "staging"

env:
  AWS_REGION: us-east-1                        
  ECR_REPOSITORY: assignment21jul-duplicate             
  ECS_SERVICE: assignment-service
  ECS_CLUSTER: assignment-cluster
  ECS_TASK_DEFINITION: assignment-task.json                                           
  CONTAINER_NAME: assignment-container
  
permissions:
  contents: read

jobs:
 pre_build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v3
      
      - name: list directory contents
        run: ls -lart
        
      - uses: actions/upload-artifact@master
        with:
          name: pre_build-artifact
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: remove previous one2oneapp-latest image for re-build
        run: aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageTag="one2oneapp-latest"
 test:
    needs : pre_build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false      
      matrix:
        language: [ 'javascript' ]
    steps:     
     - name: check out the code
       uses: actions/checkout@v3
        
     - name: Initialize CodeQL
       uses: github/codeql-action/init@v2
       with:
         queries: +security-extended
         languages: ${{ matrix.language }}

     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v1
       
          
